// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrBestPizza.MrBestDbContext;

#nullable disable

namespace MrBestPizza.Migrations
{
    [DbContext(typeof(BestDbContext))]
    partial class BestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("MrBestPizza.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pizza folded in half turnover-style.",
                            Name = "Calzone"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Small pizza served as snack.",
                            Name = "Pizzetta"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The pizza is deep-fried (cooked in oil) instead of baked.",
                            Name = "Deep-fried pizza "
                        },
                        new
                        {
                            Id = 4,
                            Description = "Distinguished by the use of non-traditional ingredients, especially varieties of fresh produce.",
                            Name = "California-style pizza"
                        });
                });

            modelBuilder.Entity("MrBestPizza.Entities.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("PizzaId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            PizzaId = 101,
                            CategoryId = 1,
                            Description = "A Pizza that enriches the soul",
                            Name = "Chicken Pizza",
                            Price = 29m
                        },
                        new
                        {
                            PizzaId = 122,
                            CategoryId = 2,
                            Description = "A Pocket friendly Pizza",
                            Name = "Beef",
                            Price = 29.7m
                        },
                        new
                        {
                            PizzaId = 1123,
                            CategoryId = 4,
                            Description = "A blend of nutrient",
                            Name = "Seasoned",
                            Price = 23.8m
                        },
                        new
                        {
                            PizzaId = 127,
                            CategoryId = 4,
                            Description = "Specially made for you",
                            Name = "Spicy Pizza",
                            Price = 50m
                        },
                        new
                        {
                            PizzaId = 324,
                            CategoryId = 3,
                            Description = "A blend of vegetables",
                            Name = "Vegie Pizza",
                            Price = 46.5m
                        },
                        new
                        {
                            PizzaId = 453,
                            CategoryId = 2,
                            Description = "Pizza de French",
                            Name = "French Pizza",
                            Price = 45.6m
                        },
                        new
                        {
                            PizzaId = 1009,
                            CategoryId = 1,
                            Description = "No beef Just plain",
                            Name = "Plain ",
                            Price = 34.8m
                        });
                });

            modelBuilder.Entity("MrBestPizza.Entities.Pizza", b =>
                {
                    b.HasOne("MrBestPizza.Entities.Category", "category")
                        .WithMany("pizza")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("MrBestPizza.Entities.Category", b =>
                {
                    b.Navigation("pizza");
                });
#pragma warning restore 612, 618
        }
    }
}
